### ISSUE TITLE
Could you add a license

### ISSUE THREAD

**Issue by konekoya** [damikun/React-Toast#1]
Hi @damikun,

We plan to use your awesome library in our project but haven't found any license in this Repo. Could you add one so it's clear if this library can be used for free or not. Thanks 🙏

**Comment by damikun** [comment]
Hi @konekoya 

I edited license as MIT so no problem to copy and use... 

I will release package soon, but I do not have much time yet to do that.. (so no package on _npm_ yet... )  You can copy the folders with toast and do it by yourself or just use plain project... 

So for now you must extract toast from  **src/components/Toast**  (https://github.com/damikun/React-Toast/tree/main/src/Components/Toast) this is plain toast.. folder... (no dependency to other folders... )

Don`t forget to purge TailwindCSS to reduce bundle size.. But for dev.. keep it disabled.... much easy... 

The purge control is available under tailwind.config.js you can read more on docs.. https://tailwindcss.com/docs/optimizing-for-production#enabling-manually it is enabled and should work fine  :)
