### ISSUE TITLE
There is no exported ToastProvider from 'react-toast', neither default nor named

### ISSUE THREAD

**Issue by madrus** [damikun/React-Toast#4]
**Describe the bug**
There is no exported ToastProvider from 'react-toast', neither default nor named.

**To Reproduce**
1. install: `yarn add react-toast`
2. add `import ToastProvider from 'react-toast'`, `import { ToastProvider } from 'react-toast'`
3. compile the project
4. see the error that ToastProvider is not being exported

**Expected behavior**
To be able to follow your main README we need to able to import ToastProvider.

**Desktop (please complete the following information):**
 - OS: MacOS BigSur

**Additional context**
I have checked the `node_modules/react-toast` folder. This is what is being exported from your NPM-package:

```js
export { default as ToastContainer } from './ToastContainer';
export { toast } from './toast';
```

**Comment by damikun** [comment]
Hello @madrus there **is no** official package on npm.. This exist only as GitHub project... I did not had time to do it.. I only exported part from my UI lib as GitHub repo.. So it is impossible to run `yarn add react-toast` since I did not publish this on `npm`

If there is something in project from old testing I will look and delete it...

**Comment by madrus** [comment]
Hi @damikun, thanks for clarifying. However, I did install it exactly like that :smiley: : `yarn add react-toast`. That is why I could check the package contents and see the definition files in it. Just in my node_modules/react-toast folder.

But I got your point and tested the package. Came to a conclusion that I cannot use it unfortunately, much that I would love it, without changing the package itself. Mostly because the ToastContainer does not accept styling as a parameter. Only backgroundColor and color. But for example, I cannot make the toast look like the one in your gif. For that I need to do lots of overrides. However, you gave me enough food for thought, so I will try and figure out something for myself based on your package.

Anyways, good job! I am very impressed how you did it.

**Comment by damikun** [comment]
Yes idea was just to share code.. maybe there is some dummy test on npm from past but it is not actual..

The demo you have under this github repo is exactly what is in sources.. you can copy and modify it by your needs..

If you need to copy it to project there is just 3 files in Toast folder under UIComponents + you need to setup tailwind if you all-ready have not

I all-ready updated the toast in my internal UI kit.. One day when i will have more time i will reupload all with official package :)

**Comment by madrus** [comment]
Got you! Thanks again. Will do.
